services:
  api:
    build:
      context: ...
      dockerfile: ERPSystem/Dockerfile
    container_name: erp_api
    ports:
      - "5000:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: erp_postgres
    restart: always
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
      POSTGRES_DB: erp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: